/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Страница предстоящих встреч — общий список бронирований всех типов. */
        get: operations["listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEventTypes"];
        put?: never;
        post: operations["createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventType"];
        put: operations["updateEventType"];
        post?: never;
        /**
         * @description Удалить тип события.
         *     409 — у типа события есть брони, удаление заблокировано.
         */
        delete: operations["deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронь на выбранный слот.
         *
         *     Сервер не доверяет клиенту и заново проверяет свободность `start`:
         *     409 — слот уже занят, 422 — `start` вне сетки/окна, 404 — нет типа события.
         *     При успехе `end` и `status: confirmed` проставляет сервер.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Витрина видов брони: название, описание, длительность. */
        get: operations["browseEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["viewEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для типа события в диапазоне дат.
         *
         *     `from` и `to` — календарные даты, трактуются в таймзоне конфига (`PublicConfig.timezone`).
         *     Сервер пересекает [from, to] с окном бронирования (14 дней от «сейчас»)
         *     и рабочими часами из конфига, нарезает по длительности типа события
         *     с шагом `slotStepMinutes` и вычитает пересечения с непогашенными бронями.
         *     Слоты не пересекаются, смежные допустимы: [start, end).
         */
        get: operations["listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование гостя. */
        Booking: {
            id: string;
            eventTypeId: string;
            guestName: string;
            /** Format: email */
            guestEmail?: string;
            /** Format: date-time */
            start: string;
            /**
             * Format: date-time
             * @description = `start` + `durationMinutes` типа события. Проставляет сервер.
             */
            end: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Тело запроса на бронирование. */
        BookingInput: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота. Должно совпасть с одним из свободных слотов.
             */
            start: string;
            guestName: string;
            /** Format: email */
            guestEmail?: string;
        };
        /**
         * @description Статус брони. В v1 — только подтверждённые: отмены/переноса нет.
         * @enum {string}
         */
        BookingStatus: "confirmed";
        /** @description Тип события, которым управляет владелец. */
        EventType: {
            /** @description Идентификатор. Генерируется сервером. */
            id: string;
            title: string;
            description?: string;
            /**
             * @description Длительность встречи. В v1 — только два режима.
             * @enum {number}
             */
            durationMinutes: 15 | 30;
        };
        /** @description Нельзя удалить тип события, у которого есть существующие брони. */
        EventTypeHasBookings: {
            /** @enum {string} */
            code: "event_type_has_bookings";
        };
        /**
         * @description Тело запроса на создание/изменение типа события.
         *     Без `id` — его проставляет сервер; пользователь задаёт только нейминг.
         */
        EventTypeInput: {
            title: string;
            description?: string;
            /** @enum {number} */
            durationMinutes: 15 | 30;
        };
        /** @description `start` не бьётся с сеткой слотов или лежит вне окна бронирования. */
        InvalidSlot: {
            /** @enum {string} */
            code: "invalid_slot";
        };
        NotFound: {
            /** @enum {string} */
            code: "not_found";
        };
        /** @description Публичная часть конфига доступности — нужна фронту для рендера календаря. */
        PublicConfig: {
            /** @description Например, "Europe/Moscow". */
            timezone: string;
            /**
             * Format: int32
             * @description Горизонт бронирования, в v1 — 14.
             */
            bookingWindowDays: number;
            /**
             * Format: int32
             * @description Шаг сетки свободных слотов в минутах, в v1 — 15.
             */
            slotStepMinutes: number;
            workingHours: components["schemas"]["WorkingHours"];
        };
        /** @description Вычисляемый свободный слот (не хранится, только читается гостем). */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота. Слоты не пересекаются, смежные допустимы: [start, end).
             */
            start: string;
            /** Format: date-time */
            end: string;
        };
        /** @description Слот уже занят к моменту брони (в т.ч. гонка двух гостей за один слот). */
        SlotUnavailable: {
            /** @enum {string} */
            code: "slot_unavailable";
        };
        /** @description Рабочие часы владельца — фиксированная часть конфига доступности. */
        WorkingHours: {
            /** @description Дни недели приёма (1 = Пн … 7 = Вс). */
            days: number[];
            /** @description Начало рабочего окна в таймзоне конфига, например "09:00". */
            start: string;
            /** @description Конец рабочего окна в таймзоне конфига, например "18:00". */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBookings: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Нельзя удалить тип события, у которого есть существующие брони. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeHasBookings"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Слот уже занят к моменту брони (в т.ч. гонка двух гостей за один слот). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotUnavailable"];
                };
            };
            /** @description `start` не бьётся с сеткой слотов или лежит вне окна бронирования. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidSlot"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    browseEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    viewEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    listSlots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
}
